Copied from contact me offer.  Need to edit for WLS on AKS
oracle/weblogic-azure pull request #18
Opened 2021-08-25 18:42 UTC by edburns

new file:   weblogic-azure-aks/src/main/resources/marketing-artifacts/README.md

2021-08-31 14:15 UTC, rjeberhard approved these changes

2021-08-31 15:52 UTC, rosemarymarano reviewed
Minor edits

2021-08-31 15:52 UTC, rosemarymarano commented on weblogic-azure-aks/src/main/resources/marketing-artifacts/README.md
> +<p>Azure Oracle WebLogic Server (WLS) offers enable you to embrace cloud computing by providing greater choice and flexibility for WLS migration including lift and shift of your Java applications to
load-balancing -> load balancing

2021-08-31 15:52 UTC, rosemarymarano commented on weblogic-azure-aks/src/main/resources/marketing-artifacts/README.md
> +<p>There are a number of offers that support different common use cases such as a single working instance with Admin Server enabled as well as highly available clusters.</p>
cases, (comma) such as a single working instance with an Administration Server enabled, (comma) as

2021-08-31 15:52 UTC, rosemarymarano commented on weblogic-azure-aks/src/main/resources/marketing-artifacts/README.md
> +<p>The offers are linked in the <i>Learn more</i> section at the bottom of this page. You should feel free to give them a try, the offers are available free of charge.</p>
For more information about the offers, see [Learn More](https://www.oracle.com/middleware/technologies/weblogic.html).
give them a try, the offers -> give them a try; (semi-colon) the offers

2021-08-31 15:52 UTC, rosemarymarano commented on weblogic-azure-aks/src/main/resources/marketing-artifacts/README.md
> +<p>This offer supports a range of operating system, Java and WebLogic versions such as WLS 14 and JDK 11 on Oracle Linux 7.6 through base images. These base images are also available on Azure on thei
This offer supports a range of operating system, -> These offers support a range of operating systems,

2021-08-31 15:52 UTC, rosemarymarano commented on weblogic-azure-aks/src/main/resources/marketing-artifacts/README.md
> +<p>This offer creates a highly available cluster of WLS virtual machines. The Administration Server and all managed servers are started by default, which allow you to manage the domain.</p>
all managed servers -> all the Managed Servers

2021-08-31 15:52 UTC, rosemarymarano commented on weblogic-azure-aks/src/main/resources/marketing-artifacts/README.md
> +[Learn More](https://www.oracle.com/middleware/technologies/weblogic.html)
You don't need to keep this link here because I reproduced it earlier in the doc, but you can keep it here, too, if you want.

2021-09-01 17:59 UTC, mriccell requested changes

2021-09-01 18:07 UTC, rosemarymarano commented on weblogic-azure-aks/src/main/resources/marketing-artifacts/README.md
> +<p>Azure Oracle WebLogic Server (WLS) offers enable you to embrace cloud computing by providing greater choice and flexibility for WLS migration including lift and shift of your Java applications to
I re-read this several times too, "Azure Oracle WebLogic Server (WLS) offers enable you..." I think that they are referring the the Azure Oracle WLS **offers** not just to Azure Oracle WLS.

2021-09-01 18:10 UTC, mriccell commented on weblogic-azure-aks/src/main/resources/marketing-artifacts/README.md
> +<p>Azure Oracle WebLogic Server (WLS) offers enable you to embrace cloud computing by providing greater choice and flexibility for WLS migration including lift and shift of your Java applications to
I see thanks for the clarification

2021-10-22 17:11 UTC, merged