Support MySQL integration
oracle/weblogic-azure pull request #192
Opened 2022-08-10 04:48 UTC by galiacheng

Changes include:

- Add MySQL as an option in UI -> DB blade.
- Use env variables to pass parameters to deployment script in DB template.

2022-08-10 07:59 UTC, galiacheng commented
Working with SSL version issue on GA images

2022-08-10 23:21 UTC, edburns commented on weblogic-azure-aks/src/main/arm/scripts/setupDBConnections.sh
> -    echo_stdout "${usage}"
While I support the idea of no longer reading a very long list of parameters from stdin, and instead using environment variables, I do not support losing the helpful usage message.  Please restore the usage message and make it clear what environment variables this script requires to function correctly.

2022-08-10 23:27 UTC, edburns commented on weblogic-azure-aks/src/main/bicep/modules/_deployment-scripts/_ds-datasource-connection.bicep
> +      {
Yes, this is much cleaner.  I have filed a [User Story](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1590695) to apply this approach throughout the offer.

2022-08-10 23:28 UTC, edburns requested changes
One cosmetic change requested, regarding the `usage` function.

2022-08-17 17:51 UTC, edburns approved these changes

2022-08-19 13:26 UTC, mriccell approved these changes

2022-08-19 13:26 UTC, merged