UI-Change: Update datatype to make it consistent with JBoss and WebSphere
oracle/weblogic-azure pull request #275
Opened 2023-07-28 08:23 UTC by backwind1233

## Context
The database type options in the solution are inconsistent with what're in JBoss and WebSphere.  The options should focus on database brand type, so that to remove confusion.

https://aka.ms/wls-vm-cluster 
![image](https://github.com/oracle/weblogic-azure/assets/4465723/3deadbac-fa97-43aa-bb72-369ae2084d98)

## Follow-up task
- [ ] The sentences and images in this javaee passwordless ⁠[Configure passwordless database connections for Java apps on Oracle WebLogic Servers](https://learn.microsoft.com/en-us/azure/developer/java/ee/how-to-configure-passwordless-datasource?tabs=mysql-flexible-server) also need change.

2023-07-28 08:24 UTC, backwind1233 commented
Hello @edburns, could you review this PR?

2023-07-28 18:25 UTC, edburns requested changes
Hello @backwind1233 , I understand the intent of this PR is to make the labels consistent with JBoss EAP and IBM WebSphere. However, there are multiple priorities to consider.

The most important priority regarding labels in a UI is consistency with Microsoft brand.  Let's consider the proposed changes.

1. `s/Azure database for PostgreSQL (with support for passwordless connection)/PostgreSQL (Support passwordless connection)/g`

   Neither label is consistent with MS Branding. See [C+AI Style Guide](https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=42335). Also, the proposed change to the parenthetical statement is less gramattically correct.  The correct replacement is:
   
   `Microsoft Azure Database for PostgreSQL (with support for passwordless connection)`

1. `s/Azure SQL (with support for passwordless connection)/Microsoft SQL Server (Support passwordless connection)/g`

   Neither label is consistent with MS Branding. See [C+AI Style Guide](https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=27534). Also, the proposed change to the parenthetical statement is less gramattically correct.  The correct replacement is:
   
   `Microsoft Azure SQL Database (with support for passwordless connection)`
   
1. `s/MySQL (with support for passwordless connection)/MySQL (Support passwordless connection)/g`

   Neither label is consistent with MS Branding. See [C+AI Style Guide](https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=42334). Also, the proposed change to the parenthetical statement is less gramattically correct.  The correct replacement is:
   
   `Microsoft Azure Database for MySQL (with support for passwordless connection)`
   
We also must make these brand changes for the labels for the non-passwordless connections.

Please make these changes in subsequent commit(s).

### MORE for you to do!

The secondary priority is consistence across our offers. We have some work to do here also.

As often happens, this apparently simple change request has turned into another instance of a cross-vendor and cross-offer exercise.

I ask you to please create a work item of type **Feature** within **Epic** [Cross-partner processes](https://dev.azure.com/edburns-msft/Open%20Standard%20Enterprise%20Java%20(Java%20EE)%20on%20Azure/_workitems/edit/386). Title: Survey and correct brand naming for Azure databases in offers.

Inside that **Feature** create work items of type **User Story** for with title "Survey and correct brand naming for Azure databases for <VENDOR>", where VENDOR is IBM, Oracle, Red Hat.

In the Oracle **User Story** list [o-152](https://dev.azure.com/weblogic-azure/Open%20Standard%20Enterprise%20Java%20(Java%20EE)%20on%20Azure/_workitems/edit/150) as a **Remote related** link.

2023-07-31 05:46 UTC, backwind1233 commented
Hello, @edburns 
To my understanding, you thought that the consistency of Microsoft brand has a higher priority than the consistency between offers, right?

> We also must make these brand changes for the labels for the non-passwordless connections.
I am not very sure about the intention of this sentence, could you give me more explanation?


> ...
> In the Oracle User Story list [o-152](https://dev.azure.com/weblogic-azure/Open%20Standard%20Enterprise%20Java%20(Java%20EE)%20on%20Azure/_workitems/edit/150) as a Remote related link.

[Feature](https://dev.azure.com/edburns-msft/Open%20Standard%20Enterprise%20Java%20(Java%20EE)%20on%20Azure/_workitems/edit/4215) created.

2023-08-01 22:09 UTC, edburns approved these changes

2023-08-02 18:35 UTC, mriccell approved these changes

2023-08-02 18:35 UTC, merged