On branch edburns-msft-78-contact-me-verbiage Extract current verbiage
oracle/weblogic-azure pull request #79
Opened 2021-11-05 17:22 UTC by edburns

Your branch is up to date with 'origin/edburns-msft-78-contact-me-verbiage'.
deleted:    arm-oraclelinux-wls/src/main/resources/description.html
modified:   arm-oraclelinux-wls/src/main/resources/README.md

Signed-off-by: Ed Burns <edburns@microsoft.com>

2021-11-05 20:11 UTC, edburns commented
Hello @rosemarymarano  and @mriccell , this README is our way to allow interested parties to control the text of the [CONTACT ME offer](https://aka.ms/azurewls). When the PR is merged, I will update Partner Center with the text in the README so that when the offer is re-published, the changes will appear.

2021-11-05 20:19 UTC, edburns commented
Please give your editorial suggestions, I will apply them, and we will go through the normal review process.

2021-11-05 20:33 UTC, mriccell requested changes

2021-11-05 20:33 UTC, mriccell commented on weblogic-azure-vm/arm-oraclelinux-wls/src/main/resources/README.md
> +<p>Azure Oracle WebLogic Server (WLS) offers enable you to embrace cloud computing by making it as easy as possible to migrate your Java applications to Azure. The offers increase productivity by aut
have we not been calling it Oracle WebLogic Server on Azure offers?

2021-11-05 20:33 UTC, mriccell commented on weblogic-azure-vm/arm-oraclelinux-wls/src/main/resources/README.md
> +<p>There are several offers that target use cases such as single node with admin server enabled and WLS cluster (including dynamic cluster). These offers supports a range of operating system, Java an
admin server -> Administration server
(including dynamic cluster) -> (including both configured and dynamic clusters)

2021-11-05 20:33 UTC, mriccell commented on weblogic-azure-vm/arm-oraclelinux-wls/src/main/resources/README.md
> +The WLS on AKS offer automates provisioning an AKS cluster, the WebLogic Kubernetes Operator, WLS Docker images and the Azure Container Registry (ACR). The offer also supports configuring load balanc
WLS on AKS -> The WebLogic on AKS
such as 12.2.1.3 and 12.2.1.4 how about 14.1.1?

2021-11-05 20:33 UTC, mriccell commented on weblogic-azure-vm/arm-oraclelinux-wls/src/main/resources/README.md
> +<p>Oracle and Microsoft also provide basic step-by-step guidance on <a href=” https://techcommunity.microsoft.com/t5/apps-on-azure/run-oracle-weblogic-server-on-azure-kubernetes-service/ba-p/1849719”
WLS on AKS -> The WebLogic on AKS

2021-11-05 20:33 UTC, mriccell commented on weblogic-azure-vm/arm-oraclelinux-wls/src/main/resources/README.md
> +The WLS on virtual machines offers automate provisioning virtual network, storage, and Linux resources, installing WLS, setting up security with a network security group, easing database connectivity
WLS on virtual machines -> WebLogic on virtual machines

2021-11-08 23:23 UTC, edburns commented
Applied changes in 1322525 .

2021-11-10 22:13 UTC, edburns commented on weblogic-azure-vm/arm-oraclelinux-wls/src/main/resources/README.md
>  * [Documentation](https://wls-eng.github.io/arm-oraclelinux-wls/)
Great catch. It is not.  It should be https://oracle.github.io/weblogic-azure/

2021-11-10 22:47 UTC, mriccell commented on weblogic-azure-vm/arm-oraclelinux-wls/src/main/resources/README.md
> +<p>There are several offers that target use cases such as single node with Administration server enabled and WLS cluster (including both configured and dynamic clusters). These offers supports a rang
WLS 14 -> 14.1.1.0 
the images can be on Oracle Linux 7.6 or Oracle Linux 8.4

2021-11-10 22:47 UTC, mriccell commented on weblogic-azure-vm/arm-oraclelinux-wls/src/main/resources/README.md
> +The WebLogic Server on AKS offer automates provisioning an AKS cluster, the WebLogic Kubernetes Operator, WLS Docker images and the Azure Container Registry (ACR). The offer also supports configuring
such as 14.1.1 -> 14.1.1.0

2021-11-10 23:20 UTC, edburns commented
Resolved in 44d9f20.

2021-11-10 23:43 UTC, mriccell approved these changes

2021-11-10 23:43 UTC, merged